name: client
version: 1.0.0+1
publish_to: none
description: Flutter Boilerplate Clean Architecture
environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  envify: ^2.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  get: 4.6.5

dev_dependencies:
  build_runner: ^2.1.8
  envify_generator: ^2.0.2
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.3+1
  flutter_rename_app_plus: ^1.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1

flutter:
  assets:
    - assets/images/
  # For Custom Font Usage uncomment the example below
  #fonts:
  #  - family: avenir
  #    fonts:
  #      - asset: assets/fonts/avenir/AvenirLTPro-Medium.otf
  #        weight: 400
  #        style: normal
  #  - family: avenir-italic
  #    fonts:
  #      - asset: assets//fonts/avenir/AvenirLTPro-Oblique.otf
  #        style: italic
  #        weight: 400
  #  - family: avenir-bold
  #    fonts:
  #      - asset: assets/fonts/avenir/AvenirLTPro-Heavy.otf
  #        weight: 800
  #        style: normal
  uses-material-design: true

flutter_rename_app_plus:
  application_name: Client
  dart_package_name: Client
  application_id: dev.goldcoders.client
  bundle_id: dev.goldcoders.client
  android_package_name: dev.goldcoders.client
