name: client
version: 1.0.0+1
publish_to: none
description: Flutter Boilerplate Clean Architecture
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  envify: ^2.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.1.8
  envify_generator: ^2.0.2
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

